accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('delete<int:user_id>', views.delete, name='delete'),

    path('edit', views.edit, name='edit'),
    path('listing', views.listing, name='listing'),
    path('reset', views.reset, name='reset'),
    path('search', views.search, name='search'),

]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('search', views.search, name='search'),
    path('search_adv', views.search_adv, name="search_adv"),
    path('listing', views.listing, name='listing'),
    path('edit', views.edit, name='edit'),
    path('add', views.add, name='add'),
    path('about/<int:book_id>', views.about, name='about'),
    path('delete/<int:book_id>', views.delete, name='delete'),
    path('borrow/<int:book_id>', views.borrow, name='borrow'), 
    path('check_in/<int:book_id>', views.check_in, name='check_in'),  
]

library/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('books/'   , include('books.urls', namespace='books')),
    path('accounts/', include('accounts.urls', namespace='accounts')),  
    path('records/' , include('records.urls' , namespace='records')),
    path('events/'  , include('events.urls' , namespace='events')),
    path('admin/', admin.site.urls),
]

# register media url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

from django.shortcuts import redirect, get_object_or_404
from django.contrib import messages, auth
from django.contrib.auth.models import User

from books.models import Book
from records.models import BorrowRecord
from books.choices import language_choices, category_choices

# Create your views here.

def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            messages.success(request, "You are logged in !")
            return redirect("accounts:dashboard")
        else:
            messages.error(request, "Invalid credentials !")
            return redirect("accounts:login")
    return render(request, 'accounts/login.html')

def logout(request):
    if request.method == "POST":
        auth.logout(request)
        messages.success(request, "You are now logged out !")        
    return redirect("pages:index") 

def register(request):
    if (request.method == "POST"):
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, "Username already exists !")
                return redirect("accounts:register")
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request,"Email already exists !")
                    return redirect("accounts:register")
                else:
                    user = User.objects.create_user(username=username, password=password, email=email, first_name=first_name, last_name=last_name)
                    user.save()
                    messages.success(request, "Account created successfully !")
                    return redirect("accounts:login")
        else:
            messages.error(request, "Passwords do not match !")
            return redirect("accounts:register")
    else:
        return render(request, 'accounts/register.html')
    return render(request, 'accounts/register.html')

def delete(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    user.delete()
    return redirect('accounts:dashboard')

def dashboard(request):
    # staff : NEW book arrival in past week + book borrrow out
    # user  : borrowed books + recommended book list
    listings = BorrowRecord.objects.all() # filter(status__iexact='borrowed')
    if (request.user.is_staff):
        booklists = Book.objects.order_by('-date_arrived')[:5]
    else:
        listings = listings.filter(user=request.user)
        booklists = Book.objects.order_by('-date_arrived')[:5]
    context = {"language_choices" : language_choices, 
               "category_choices" : category_choices, 
               "listings" : listings , "booklists" : booklists }
    return render(request, 'accounts/dashboard.html', context)

def reset(request):
    return render(request, 'accounts/reset.html')

def search(request):
    listings = User.objects.order_by('username')
    if (request.method == "POST"):
        if 'username' in request.POST:
            username = request.POST['username']
            if username:      
                listings = listings.filter(username__icontains=username)
        if 'first_name' in request.POST:
            first_name = request.POST['first_name']
            if first_name:           
                listings = listings.filter(first_name__iexact=first_name)
        if 'last_name' in request.POST:
            last_name = request.POST['last_name']
            if last_name:
                listings = listings.filter(last_name__iexact=last_name)
        if 'email' in request.POST:
            email = request.POST['email']
            if email:
                listings = listings.filter(email__iexact=email)
    context = { "listings": listings, }     
    return render(request, 'accounts/search.html', context)

def edit(request):
    return render(request, 'accounts/edit.html')

def listing(request):
    listings = User.objects.all()
    context = {'listings' : listings }
    return render(request, 'accounts/listing.html', context)

templates/accounts/dashboard.html
{% extends "base.html" %} 
{% block title %}Edit Account{% endblock title %}
{% block content %}
{% load static %}

<!-- Hero Section -->
<section class="hero">

    {% if user.is_staff %}
      {% if booklists %}    

        <div class="row">
          <div class="col-md-12">
            <h2> New books arrive recently </h2> 
            <table class="table">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Author</th>
                  <th>ISBN</th>
                  <th>Language</th>
                  <th>Category</th>
                </tr>
              </thead>

              <tbody>
                {% for listing in booklists %}
                <tr>
                  <td>{{ listing.title }}</td>
                  <td>{{ listing.author }}</td>
                  <td>{{ listing.isbn }}</td>
                  {% if listing.language in language_choices %}
                  {%  for key, value in language_choices.items %}
                  {% if key == listing.language %}
                  <td>{{ value }}</td>
                  {% endif %}
                  {% endfor %}
                  {% else %}
                  <td></td>
                  {% endif %}
                  {% if listing.category in category_choices %}
                  {%  for key, value in category_choices.items %}
                  {% if key == listing.category %}
                  <td>{{ value }}</td>
                  {% endif %}
                  {% endfor %}
                  {% else %}
                  <td>{{ listing.category | title }}</td>
                  {% endif %}

                </tr>
                {% endfor %}
            </tbody>  
            </table>
          </div>
        </div>

      {% endif %}
    {% endif %}


        {% if listings %}
        <div class="row">
          <div class="col-md-12">
            {% if user.is_staff %}
            <h2> Books check out recently </h2> 
            {% else %}
            <h2> Welcome {{ user.first_name | title }} </h2>
            <h3> Current Borrow List </h3>
            {% endif %}
            <br/>
            <table class="table">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Due Date</th>
                </tr>
              </thead>

              <tbody>
                {% for listing in listings %}
                <tr>
                  <td>{{ listing.book.title }}</td>
                  <td>{{ listing.due_date }}</td>
                  {% if not user.is_staff %}
                  <td>
                    {% if listing.due_date|date:"Y-m-d" > now|date:"Y-m-d" %}
                    <a class="btn btn-primary" href="{% url 'books:check_in' listing.book.id %}">Book Return</a>
                    {% else %}
                    <a class="btn btn-danger" href="{% url 'books:check_in' listing.book.id %}">Book Return</a>
                    {% endif %}
                  </td>
                  {% endif %}
                </tr>
                {% endfor %}

            </tbody>  
            </table>
          </div>
        </div>
        {% else %}   
        {% if user.is_staff %}
        <h2>No user borrow book</h2>
        {% else %}
        <h2>No book is borrowed</h2>
        {% endif %}
        {% endif %}




</section>

    <!-- Book Showcase -->
    {% if booklists and not user.is_staff %}
    <section class="book-showcase">
        <h2 class="section-title">Books you may interest in</h2>
        <div class="books">
            {% for listing in booklists %}
              <div class="book" data-url={% url 'books:about' listing.id %} onclick="window.location.href=this.getAttribute('data-url')">
                {% if listing.cover_url %}
                <div class="book-cover" style="background-image: url('{{ listing.cover_url.url }}');"></div>
                {% else %}
                <div class="book-cover" style="background-image: url('{% static "img/book.jpeg" %}');"></div>
                {% endif %}
                <div class="book-info">
                    <div class="book-title">{{ listing.title | title }}</div>
                    <div class="book-author">{{ listing.author | title }}</div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
    {% endif %}

{% endblock content  %}

templates/accounts/edit.html
{% extends "base.html" %} 
{% block title %}Edit Account{% endblock title %}
{% block content %}


 <section id="register" class="hero">
        <div class="row">
          <div class="col-md-6 mx-auto">

            <div class="card">
              <div class="card-header bg-primary text-white">
                <h4><i class="fas fa-user-plus"></i> Register</h4>
              </div>
              <div class="card-body">
                <form action={% url 'accounts:register' %} method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input
                      id="first_name"
                      type="text"
                      name="first_name"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input
                      id="last_name"
                      type="text"
                      name="last_name"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input
                      id="username"
                      type="text"
                      name="username"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="email">Email</label>
                    <input
                      id="email"
                      type="email"
                      name="email"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="phone">Phone</label>
                    <input
                      id="phone"
                      type="text"
                      name="phone"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="address">Address</label>
                    <input
                      id="address"
                      type="text"
                      name="address"
                      class="form-control"
                      required
                    />
                  </div>

                  <input
                    type="submit"
                    value="Save"
                    class="btn btn-secondary btn-block"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
        
</section>

{% endblock content  %}

templates/accounts/listing.html
{% extends "base.html" %} 
{% block title %} List Accounts {% endblock title %}
{% block content %}

    <section id="dashboard" class="hero">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2>Welcome </h2>

            {% if listings %}
            <table class="table">
              <thead>
                <tr>
                  <th>status</th>
                  <th>User Name</th>
                  <th>Last Name</th>
                  <th>Last Login</th>
                </tr>
              </thead>
              <tbody>
                {% for listing in listings %}
                <tr>
                  <td>{{ listing.is_active }}</td>
                  <td>{{ listing.username }}</td>
                  <td>{{ listing.last_name | title}}</td>
                  <td>{{ listing.last_login }}</td>
                  <td>
                    <button class="btn btn-danger" data-url="{% url 'accounts:delete' listing.id %}" data-id="{{ listing.id }}" data-toggle="modal" data-target="#deleteConfirmModal" >Delete</button>
                  </td>
                </tr>
                {% endfor %}
            </tbody>  
            </table>
            {% endif %}
          </div>
        </div>
      </div>

        
    <div class="modal fade" id="deleteConfirmModal" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
            <button type="button" class="close" data-dismiss="modal">
              <span>&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete ?</p>
            <a id="confirmDeleteBtn" class="btn btn-danger" href="#">
              Yes
            </a>
            <button class="btn btn-info" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>



    </section>

{% endblock content  %}

templates/accounts/login.html
{% extends "base.html" %} 
{% block title %}Login{% endblock title %}
{% block content %}

   <section id="login" class="hero">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto">

            <div class="card">
              <div class="card-header bg-primary text-white">
                <h4><i class="fas fa-sign-in-alt"></i> Login</h4>
              </div>
              <div class="card-body">
                <form action={% url 'accounts:login' %} method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input
                      id="username"
                      type="text"
                      name="username"
                      class="form-control"
                      required
                    />
                  </div>

                  <div class="form-group">
                    <label for="password2">Password</label>
                    <input
                      id="password"
                      type="password"
                      name="password"
                      class="form-control"
                      required
                    />
                  </div>

                  <input
                    type="submit"
                    value="Login"
                    class="btn btn-secondary btn-block"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content  %}

templates/accounts/register.html
{% extends "base.html" %} 
{% block title %}Register{% endblock title %}
{% block content %}

<section id="register" class="hero">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto">

            <div class="card">
              <div class="card-header bg-primary text-white">
                <h4><i class="fas fa-user-plus"></i> Register</h4>
              </div>
              <div class="card-body">
                <form action={% url 'accounts:register' %} method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input
                      id="first_name"
                      type="text"
                      name="first_name"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input
                      id="last_name"
                      type="text"
                      name="last_name"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input
                      id="username"
                      type="text"
                      name="username"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="email">Email</label>
                    <input
                      id="email"
                      type="email"
                      name="email"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input
                      id="password"
                      type="password"
                      name="password"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input
                      id="password2"
                      type="password"
                      name="password2"
                      class="form-control"
                      required
                    />
                  </div>
                  <input
                    type="submit"
                    value="Register"
                    class="btn btn-secondary btn-block"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
</section>

{% endblock content  %}

templates/accounts/reset.html
{% extends "base.html" %} 
{% block title %} Reset Password {% endblock %}
{% block content %}

   <section id="reset" class="hero">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto">

            <div class="card">
              <div class="card-header bg-primary text-white">
                <h4><i class="fas fa-sign-in-alt"></i>Reset Password</h4>
              </div>
              <div class="card-body">
                <form action={% url 'accounts:reset' %} method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input
                      id="username"
                      type="text"
                      name="username"
                      class="form-control"
                      required
                    />
                  </div>

                  <div class="form-group">
                    <label for="email">Email</label>
                    <input
                      id="email"
                      type="email"
                      name="email"
                      class="form-control"
                      required
                    />
                  </div>

                  <input
                    type="submit"
                    value="Reset"
                    class="btn btn-secondary btn-block"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content  %}

templates/accounts/search.html
{% extends "base.html" %} 
{% block title %} Search {% endblock %}
{% block content %}

<section class="hero">

            <div class="search">
              <h2> Account </h2>
              <form action="{% url "accounts:search" %}"  method="POST">
                {% csrf_token %}
                <!-- Form Row 1 -->
                <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <label class="sr-only">First Name</label>
                    <input
                      type="text"
                      name="first_name"
                      class="form-control"
                      placeholder="First Name"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">User Name</label>
                    <input
                      type="text"
                      name="username"
                      class="form-control"
                      placeholder="User Name"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Phone</label>
                    <input
                      type="text"
                      name="phone"
                      class="form-control"
                      placeholder="Phone"
                    />
                  </div>

                </div>
                <!-- Form Row 2 -->
                <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Last Name</label>
                    <input
                      type="text"
                      name="last_name"
                      class="form-control"
                      placeholder="Last Name"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Email</label>
                    <input
                      type="text"
                      name="email"
                      class="form-control"
                      placeholder="Email"
                    />
                  </div>

                </div>
                <button class="btn btn-secondary btn-block mt-4" type="submit">
                  Search
                </button>
              </form>
            </div>   

        <div class="row">
          <div class="col-md-12">
            <br \>
            {% if listings %}
            <table class="table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>status</th>
                  <th>User Name</th>
                  <th>Last Name</th>
                  <th>Last Login</th>
                </tr>
              </thead>
              <tbody>
                {% for listing in listings %}
                <tr>
                  <td>{{ listing.id }}</td>
                  <td>{{ listing.is_active }}</td>
                  <td>{{ listing.username }}</td>
                  <td>{{ listing.last_name | title}}</td>
                  <td>{{ listing.last_login }}</td>
                  <td>
                    <button class="btn btn-danger" data-url="{% url 'accounts:delete' listing.id %}" data-id="{{ listing.id }}" data-toggle="modal" data-target="#deleteConfirmModal" >Delete</button>
                  </td>
                </tr>
                {% endfor %}
            </tbody>  
            </table>
            {% endif %}
          </div>
        </div>         
        
        
    <div class="modal fade" id="deleteConfirmModal" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
            <button type="button" class="close" data-dismiss="modal">
              <span>&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete ?</p>
            <a id="confirmDeleteBtn" class="btn btn-danger" href="#">
              Yes
            </a>
            <button class="btn btn-info" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>


          </section>


{% endblock content  %}