books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('search', views.search, name='search'),
    path('search_adv', views.search_adv, name="search_adv"),
    path('listing', views.listing, name='listing'),
    path('edit', views.edit, name='edit'),
    path('add', views.add, name='add'),
    path('about/<int:book_id>', views.about, name='about'),
    path('delete/<int:book_id>', views.delete, name='delete'),
    path('borrow/<int:book_id>', views.borrow, name='borrow'), 
    path('check_in/<int:book_id>', views.check_in, name='check_in'),  
]

library/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('books/'   , include('books.urls', namespace='books')),
    path('accounts/', include('accounts.urls', namespace='accounts')),  
    path('records/' , include('records.urls' , namespace='records')),
    path('events/'  , include('events.urls' , namespace='events')),
    path('admin/', admin.site.urls),
]

# register media url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models

from datetime import date
from books.choices import language_choices, category_choices


# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    isbn = models.CharField(max_length=20, unique=True)
    year = models.IntegerField()
    total = models.PositiveIntegerField(default=1)
    stock = models.PositiveIntegerField(default=1)
    date_arrived = models.DateField(default=date.today, blank=True)
    description = models.TextField(blank=True)
    language = models.CharField(max_length=50, choices=language_choices.items())
    category = models.CharField(max_length=50, choices=category_choices.items())
    cover_url = models.ImageField(upload_to='photos/', blank=True)


    class Meta:
        ordering = ('-year',)
        indexes = [models.Index(fields=['year'])]

    def __str__(self):
        return self.title

books/views.py
from django.shortcuts import render
from django.db import models


from datetime import date
from django.db.models import Q
from django.shortcuts import redirect, get_object_or_404

from django.core.paginator import Paginator
from books.models import Book
from records.models import BorrowRecord
from .choices import language_choices, category_choices, status_choices

# Create your views here.

def add(request):
    if request.method == "POST":
        title = request.POST["title"]
        author = request.POST["author"]
        # ISBN-10: ^(?:\d{9}[\dX])$      // Example: "030640615X" 
        # ISBN-13: ^(?:\d{13})$          // Example: "9780306406157" 
        isbn = request.POST["isbn"]
        year = request.POST["year"]
        total = 1 # request.POST["total"] // number of book bought
        stock = 1 # request.POST["stock"] // number of books available to borrow
        language = request.POST["language"]
        category = request.POST["category"]
        
        date_arrived = date.today()
        # description = request.POST["description"]
        # cover_url = request.POST["cover_url"]
        book = Book(title=title, author=author, isbn=isbn, year=year, total=total,
                    stock=stock, date_arrived=date_arrived,  # cover_url=cover_url, description=description,
                    language=language, category=category) 
        book.save()
    return redirect('accounts:dashboard')

def delete(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    
    listings = Book.objects.all()
    context = { "language_choices" : language_choices, 
                "category_choices" : category_choices, 
                'listings' : listings,
                "value" : request.GET }
    return render(request, 'books/listings.html', context)
    # return render(request, 'accounts/dashboard.html')

def borrow(request, book_id):
    # book = get_object_or_404(Book, pk=book_id)
    # record = BorrowRecord(user=request.user.id, book=book_id)
    # record.save()

    book = Book.objects.get(id=book_id)
    record = BorrowRecord.objects.create(user=request.user, book=book, status=status_choices['borrowed'])
    record.save()

    listings = Book.objects.all()
    context = {'listings' : listings }
    return render(request, 'books/listings.html', context)    

def check_in(request, book_id):
    book = Book.objects.get(id=book_id)
    record = BorrowRecord.objects.filter(user=request.user)
    record = record.filter(book=book)
    record.delete()
    return redirect('accounts:dashboard')    



def edit(request):
    context = {"language_choices" : language_choices, 
               "category_choices" : category_choices, 
               "values" : request.GET}
    return render(request, 'books/edit.html', context)

def listing(request):
    listings = Book.objects.all().order_by('title')
    if request.method == "POST":
        if 'title' in request.POST:
            title = request.POST['title']
            if title:      
                listings = listings.filter(title__icontains=title)
        if 'author' in request.POST:
            author = request.POST['author']
            if author:           
                listings = listings.filter(author__iexact=author)
        if 'isbn' in request.POST:
            isbn = request.POST['isbn']
            if isbn:
                listings = listings.filter(isbn__iexact=isbn)            
        if 'year' in request.POST:
            year = request.POST['year']
            if year:
                listings = listings.filter(year__iexact=year)
        if 'language' in request.POST:
            language = request.POST['language']
            if language:
                listings = listings.filter(language__iexact=language)
        if 'category' in request.POST:
            category = request.POST['category']
            if category:
                listings = listings.filter(category__iexact=category)  

    context = {"language_choices" : language_choices, 
               "category_choices" : category_choices, 
               'listings' : listings,
               "values" : request.POST}

    return render(request, 'books/search.html', context)

def search_adv(request):
    context = { "language_choices" : language_choices, 
                "category_choices" : category_choices, }   
    return render(request, 'books/search.html', context)

def search(request):
    query = request.GET.get('q', '').strip()  # Get search keyword
    if query:
        listings = Book.objects.filter(
            Q(title__icontains=query) |
            Q(author__icontains=query) |
            Q(category__icontains=query)
        ).distinct()
    else:   
        listings = Book.objects.order_by('title')
        if 'title' in request.GET:
            title = request.GET['title']
            if title:      
                listings = listings.filter(title__icontains=title)
        if 'author' in request.GET:
            author = request.GET['author']
            if author:
                listings = listings.filter(author__iexact=author)
        if 'isbn' in request.GET:
            isbn = request.GET['isbn']
            if isbn:
                listings = listings.filter(isbn__iexact=isbn)            
        if 'year' in request.GET:
            year = request.GET['year']
            if year:
                listings = listings.filter(year__iexact=year)
        if 'language' in request.GET:
            language = request.GET['language']
            if language:
                listings = listings.filter(language__iexact=language)
        if 'category' in request.GET:
            category = request.GET['category']
            if category:
                listings = listings.filter(category__iexact=category)    

    # listings = listings[::-1]
    paginator = Paginator(listings, 5)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)

    context = { "language_choices" : language_choices, 
                "category_choices" : category_choices,
                # "listings": listings,
                "listings" : paged_listings, 
                "values" : request.GET }       
    return render(request, 'books/listings.html', context)

def about(request, book_id):
    book = Book.objects.get(id=book_id)
    context = { "language_choices" : language_choices, 
                "category_choices" : category_choices,
                "listing": book } 
    return render(request, 'books/about.html', context)    

templates/books/about.html
{% extends "base.html" %} 
{% block title %} Details {% endblock %}
{% block content %}
{% load static %}
{% load humanize %}

<!-- Hero Section -->
<section class="hero">

<div class="container">
<h2>{{ listing.title }}</h2>
    <div class="row">
        <div class="col-md-4">
            <div class="image-container">
                {% if listing.cover_url %}
                <img src={{ listing.cover_url.url }} style="width: 240px; height: auto;" >
                {% else %}
                <img src={% static 'img/book.jpeg' %}  style="width: 240px; height: auto;">
                {% endif %}

                {% if user.is_authenticated %}
                  {% if user.is_staff %}
                   <button class="btn btn-danger" data-url="{% url 'books:delete' listing.id %}" data-id="{{ listing.id }}" data-toggle="modal" data-target="#deleteConfirmModal" >Delete</button>
                  {% else %}
                    <a href="{% url 'books:borrow' listing.id %}" class="btn btn-success">Borrow</a>
                  {% endif %}
                {% endif %}
              </div>
        </div>
        <div class="col-md-8">
            <div class="text-list">
                <ul>
                    <li><strong>Author  </strong>: {{ listing.author | title }}</li>
                    <li><strong>ISBN    </strong>: {{ listing.isbn }}</li>
                    <li><strong>Publish Year</strong>: {{ listing.year }}</li>      
                    <li><strong>Language</strong>: {{ listing.language | title }}</li>
                    <li><strong>Category</strong>: {{ listing.category | title }}</li>
                    <li><strong>Description </strong>: {{ listing.description }}</li>      
                </ul>
            </div>
        </div>
    </div>
</div>

    <div class="modal fade" id="deleteConfirmModal" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
            <button type="button" class="close" data-dismiss="modal">
              <span>&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete this book ?</p>
            <a id="confirmDeleteBtn" class="btn btn-danger" href="#">
              Yes
            </a>
            <button class="btn btn-info" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>

</section> 

{% endblock content  %}

templates/books/edit.html
{% extends "base.html" %} 
{% block title %} Modify {% endblock %}
{% block content %}

          <!-- Hero Section -->
          <section class="hero">
            <div class="search">
            <h2> Add Book </h2> 
              <form action="{% url "books:add" %}" method="POST">
                {% csrf_token %}
                <!-- Form Row 1 -->
                <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Title</label>
                    <input
                      type="text"
                      name="title"
                      class="form-control"
                      placeholder="Title"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Author</label>
                    <input
                      type="text"
                      name="author"
                      class="form-control"
                      placeholder="Author"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">ISBN</label>
                    <input
                      type="text"
                      name="isbn"
                      class="form-control"
                      placeholder="ISBN"
                    />
                  </div>

                </div>
                <!-- Form Row 2 -->
                <div class="form-row">

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Category</label>
                    <select name="category" class="form-control">
                      <option {% if not values.category %} selected="true" {% endif %} value="">
                        (Any Category)
                      </option>
                      {%  for key, value in category_choices.items %}
                      <option value="{{key}}" {% if key == values.category %} selected="true" {% endif %}>{{value}}</option>
                      {% endfor %}
                    </select>
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Language</label>
                    <select name="language" class="form-control">
                      <option {% if not values.language %} selected="true" {% endif %} value="">
                        (Any Language)
                      </option>
                      {%  for key, value in language_choices.items %}
                      <option value="{{key}}" {%if key == values.language %} selected="true" {% endif %}>{{value}}</option>
                      {% endfor %}
                    </select>
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Year</label>
                    <input
                      type="text"
                      name="year"
                      class="form-control"
                      placeholder="Year"
                    />
                  </div>

                </div>
                <button class="btn btn-secondary btn-block mt-4" type="submit">
                  Submit form
                </button>
              </form>
            </div>   
          </section>

{% endblock content  %}

templates/books/listings.html
{% extends "base.html" %} 
{% block title %} List {% endblock %}
{% block content %}

<!-- Hero Section -->
  <section id="dashboard" class="hero">

        <div class="row">
          <div class="col-md-12">


            {% if listings %}
            <table class="table">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Author</th>
                  <th>ISBN</th>
                  <th>Language</th>
                  <th>Category</th>
                </tr>
              </thead>

              <tbody>
                {% for listing in listings %}
                <tr>
                  <td>{{ listing.title }}</td>
                  <td>{{ listing.author }}</td>
                  <td>{{ listing.isbn }}</td>
                  {% if listing.language in language_choices %}
                  {%  for key, value in language_choices.items %}
                  {% if key == listing.language %}
                  <td>{{ value }}</td>
                  {% endif %}
                  {% endfor %}
                  {% else %}
                  <td></td>
                  {% endif %}
                  {% if listing.category in category_choices %}
                  {%  for key, value in category_choices.items %}
                  {% if key == listing.category %}
                  <td>{{ value }}</td>
                  {% endif %}
                  {% endfor %}
                  {% else %}
                  <td>{{ listing.category | title }}</td>
                  {% endif %}
                  <td><a href="{% url 'books:about' listing.id %}" class="btn btn-success">Detail</a></td>
                </tr>
                {% endfor %}
            </tbody>  
            </table>
            {% else %}
            <div class="col-md-12">
              <h2>Book is NOT found</h2>
            </div>
            {% endif %}
          </div>
        </div>



              <form action="{% url "books:search" %}" method="GET">
                <!-- Form Row 1 -->
                <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Title</label>
                    <input
                      type="hidden"
                      name="title"
                      class="form-control"
                      placeholder="Title"
                      value = "{{values.title}}"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Author</label>
                    <input
                      type="hidden"
                      name="author"
                      class="form-control"
                      placeholder="Author"
                      value = "{{values.author}}"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">ISBN</label>
                    <input
                      type="hidden"
                      name="isbn"
                      class="form-control"
                      placeholder="ISBN"
                      value = "{{values.isbn}}"
                    />
                  </div>

                </div>
                <!-- Form Row 2 -->
                <div class="form-row">

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Category</label>

                    <input
                      type="hidden"
                      name="category"
                      class="form-control"
                      placeholder=""
                      value = "{{values.category}}"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Language</label>

                    <input
                      type="hidden"
                      name="language"
                      class="form-control"
                      placeholder="English"
                      value = "{{values.language}}"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Year</label>
                    <input
                      type="hidden"
                      name="year"
                      class="form-control"
                      placeholder="Year"
                      value = "{{values.year}}"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Year</label>
                    <input
                      type="hidden"
                      name="q"
                      class="form-control"
                      placeholder="Year"
                      value = "{{values.q}}"
                    />
                  </div>

                </div>



        <div class="row">
          <div class="col-md-12">
            {% if listings.has_other_pages %}
            <ul class="pagination">
              {% if listings.has_previous %}
              <button class="page-link" type="submit" name="page" value="{{listings.previous_page_number}}">{{i}}&laquo;</button>
            
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#">&laquo;</a>
              </li>
              {% endif %}

              {% for i in listings.paginator.page_range %}
              {% if listings.number == i %}
              <li class="page-item active">
                <a class="page-link">{{i}}</a>              
              </li>
              {% else %}
              <button class="page-link" type="submit" name="page" value="{{i}}">{{i}}</button>

              {% endif %}
              {% endfor %}

              {% if listings.has_next %}
              <button class="page-link" type="submit" name="page" value="{{listings.next_page_number}}">{{i}}&raquo;</button>

              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#">&raquo;</a>
              </li>              
              {% endif %}
            </ul>
            {% endif %}
          </div>
        </div>
              </form>

    </section>

{% endblock content  %}

templates/books/search.html
{% extends "base.html" %} 
{% block title %} List {% endblock %}
{% block content %}

<!-- Hero Section -->
<section class="hero">

            <h2> Search Book </h2> 
            <div class="search">
              <form action="{% url "books:search" %}" method="GET">
                <!-- Form Row 1 -->
                <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Title</label>
                    <input
                      type="text"
                      name="title"
                      class="form-control"
                      placeholder="Title"
                      value = "{{values.title}}"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Author</label>
                    <input
                      type="text"
                      name="author"
                      class="form-control"
                      placeholder="Author"
                      value = "{{values.author}}"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">ISBN</label>
                    <input
                      type="text"
                      name="isbn"
                      class="form-control"
                      placeholder="ISBN"
                      value = "{{values.isbn}}"
                    />
                  </div>

                </div>
                <!-- Form Row 2 -->
                <div class="form-row">

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Category</label>
                    <select name="category" class="form-control">
                      <option {% if not values.category %} selected="true" {% endif %} value="">
                        (Any Category)
                      </option>
                      {%  for key, value in category_choices.items %}
                      <option value="{{key}}" {% if key == values.category %} selected="true" {% endif %}>{{value}}</option>
                      {% endfor %}

                    </select>
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Language</label>
                    <select name="language" class="form-control">
                      <option {% if not values.language %} selected="true" {% endif %} value="">
                        (Any Language)
                      </option>
                      {%  for key, value in language_choices.items %}
                      <option value="{{key}}" {%if key == values.language %} selected="true" {% endif %}>{{value}}</option>
                      {% endfor %}
                    </select>
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Year</label>
                    <input
                      type="text"
                      name="year"
                      class="form-control"
                      placeholder="Year"
                      value = "{{values.year}}"
                    />
                  </div>

                </div>
                <button class="btn btn-secondary btn-block mt-4" type="submit">
                  Search
                </button>
              </form>
            </div>   
</section> 

{% endblock content  %}