books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('search', views.search, name='search'),
    path('search_adv', views.search_adv, name="search_adv"),
    path('listing', views.listing, name='listing'),
    path('edit', views.edit, name='edit'),
    path('add', views.add, name='add'),
    path('about/<int:book_id>', views.about, name='about'),
    path('delete/<int:book_id>', views.delete, name='delete'),
    path('borrow/<int:book_id>', views.borrow, name='borrow'), 
    path('check_in/<int:book_id>', views.check_in, name='check_in'),  
]

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('add', views.add, name='add'),
    path('edit', views.edit, name='edit'),
]

library/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('books/'   , include('books.urls', namespace='books')),
    path('accounts/', include('accounts.urls', namespace='accounts')),  
    path('records/' , include('records.urls' , namespace='records')),
    path('events/'  , include('events.urls' , namespace='events')),
    path('admin/', admin.site.urls),
]

# register media url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models

# Create your models here.

class Event(models.Model):
    title = models.CharField(max_length=200, blank=False)
    event_date = models.DateField(blank=False)
    start_time = models.TimeField(blank=False)
    end_time = models.TimeField(blank=False)
    description = models.TextField(blank=False)

    class Meta:
        ordering = ('event_date',)
        indexes = [models.Index(fields=['event_date'])]

events/views.py
from django.shortcuts import render

from django.shortcuts import redirect, get_object_or_404
from .models import Event

# Create your views here.

def edit(request):
    return render(request, 'events/edit.html')

def add(request):
    if request.method == "POST":
        title = request.POST["title"]
        event_date = request.POST["event_date"]
        start_time = request.POST["start_time"]
        end_time = request.POST["end_time"]
        description = request.POST["description"]
        event = Event(title=title, event_date=event_date, 
                      start_time=start_time, end_time=end_time, 
                      description=description)
        event.save()

    return redirect('accounts:dashboard')

templates/events/edit.html
{% extends "base.html" %} 
{% block title %}Event{% endblock title %}
{% block content %}


<section id="Event" class="hero">
        <div class="row">
          <div class="col-md-6 mx-auto">


            <div class="card">
              <div class="card-header bg-primary text-white">
                <h4><i class="#"></i>Event</h4>
              </div>
              <div class="card-body">
                <form action={% url 'events:add' %} method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="title">Title</label>
                    <input
                      id="title"
                      type="text"
                      name="title"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="event_date">Date</label>
                    <input
                      id="event_date"
                      type="date"
                      name="event_date"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="start_time">Start Time</label>
                    <input
                      id="start_time"
                      type="time"
                      name="start_time"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="end_time">End Time</label>
                    <input
                      id="end_time"
                      type="time"
                      name="end_time"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="detail">Description</label>
                    <textarea
                      id="description"
                      type="text"
                      name="description"

                      rows="5"
                      class="form-control"
                      required
                    ></textarea>
                  </div>

                  <input
                    type="submit"
                    value="Save"
                    class="btn btn-secondary btn-block"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
        
</section>

{% endblock content  %}